### ISSUE TITLE
Issue about Downloading Dataset from DL4SE website

### ISSUE THREAD

**Issue by SpanShu96** [seart-group/DL4SE#39]
Thank you very much for developing this tool! It is very helpful and benefit for our research. 

However, I meet some problem when I downloaded the dataset when it finished. I used Chrome to download the dataset, but it always failed and notify me that “the file is not found”when 1gb content is downloaded (the size of dataset for downloading is 5gb in total). 

You could also check this video which replicate this problem (https://www.youtube.com/watch?v=ptXrTrVUvXI). I would like to know if there any limitation on download file size?

**Comment by dabico** [comment]
Thanks for the detailed issue description + video. I also replicated one of your queries and ran into the same issue. To answer your question: No we do not restrict the file download size. I'm pretty sure that this is a bug that crept in when changes were made to the download endpoint. I'll look into it now.

**Comment by dabico** [comment]
@SpanShu96 

Upon further investigation, I can confidently say that this is not an issue with the application code, but instead with the configuration of our reverse proxy. I am now able to fully download the replica of your dataset, meaning that you should be able to download your datasets as well. Let me know if you run into any additional issues regarding this matter.

**Comment by SpanShu96** [comment]
@dabico 

Thank you for solving this problem. We can now download the complete file from DL4SE website.
Okay, I see. Thank you very much.
