### ISSUE TITLE
Inconsistent in Generating Dataset Interface and Query Detail in Dashboard

### ISSUE THREAD

**Issue by SpanShu96** [seart-group/DL4SE#40]
Hi @dabico,

I found that the information in the interface of generating the dataset is inconsistent with the information in the query detail of the dashboard. 

For example, I select "at least 10 contributors" on the interface of generating the dataset and click the generating dataset. However, the query detail in the dashboard shows me that "min_contributors = 0" and "min_issues = 10". (see following Figures)

<img width="1136" alt="Screenshot 2023-05-31 at 11 29 39" src="https://github.com/seart-group/DL4SE/assets/134574338/641221a0-5316-4307-ad49-4b4b3fe6e4e8">

<img width="490" alt="Screenshot 2023-05-31 at 11 29 55" src="https://github.com/seart-group/DL4SE/assets/134574338/f1000c5b-9bf0-4e96-b632-4a718813f93b">

This situation confuses me. Could you kindly take a look at what happened to this issue? Is the problem in the front end?

**Comment by dabico** [comment]
https://github.com/seart-group/DL4SE/blob/32b4a0c2a099e1718fbbf0816e1ea614a723c957/dl4se-website/src/views/TaskCreateView.vue#L49-L66

Thank you for reporting, this is an actual bug introduced by refactoring. The issues filter was mapped to modify the state of the `min_contributors` value and vice-versa (🤦). I'll create a fix, and let you know as soon as it is live.

**Comment by dabico** [comment]
@SpanShu96 

I pushed the fix and redeployed, took a while because of airport WIFI. You may have to re-run your query though, since that last one used `min_issues = 10`. Apologies for the inconvenience. I'll mark this as closed. If you encounter more issues with this, feel free to drop a line.

**Comment by dabico** [comment]
@SpanShu96 

I pushed the fix and redeployed, took a while because of airport WIFI. You may have to re-run your query though, since that last one used `min_issues = 10`. Apologies for the inconvenience. I'll mark this as closed. If you encounter more issues with this, feel free to drop a line.

**Comment by SpanShu96** [comment]
@dabico 

I am sorry for replying late. Thank you for your generous help in time!

I can now generate the dataset and download it. No need to apologize! I should thank you for creating this tool, which brings convenience to my research (save time to write my own crawler):bow:. Thank you very much!

I see. I will update you if I encounter more issues.
